# Generated by Django 5.0 on 2023-12-23 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_spotify_id', models.CharField(max_length=255)),
                ('access_token_information', models.JSONField()),
                ('location_information', models.JSONField()),
                ('playlist_id', models.CharField(max_length=255)),
            ],
        ),
    ]
