# Generated by Django 5.0 on 2023-12-23 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SontiCastApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
