# Generated by Django 5.0 on 2023-12-26 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SontiCastApp', '0003_remove_user_access_token_information_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ip_address',
        ),
    ]
